=== dieggo554/repaso_xml_dom_sax/DatosAlumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Separador" type="xs:string"/>
        <xs:element ref="Alumno" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nombre" type="xs:string"/>
        <xs:element name="Nota" type="xs:string"/>
        <xs:element name="descripcion" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dieggo554/repaso_xml_dom_sax/DatosAlumnos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DatosAlumnos.xsd">
	<Separador>#</Separador>
	<Alumno>
		<Nombre>Raul Perez Goméz</Nombre>
		<Nota>4</Nota>
		<descripcion>ha suspendido el módulo y tiene que recuperarlo</descripcion>
	</Alumno>
	<Alumno>
		<Nombre>Manual Sanz Perez</Nombre>
		<Nota>8</Nota>
		<descripcion>ha superado el módulo</descripcion>
	</Alumno>
	<Alumno>
		<Nombre>Raquel López López</Nombre>
		<Nota>3</Nota>
		<descripcion>ha suspendido el módulo y tiene que recuperarlo</descripcion>
	</Alumno>
</Alumnos>
